//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinalPrj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TableCooks1081655
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableCooks1081655()
        {
            this.TableRecipes1081655 = new HashSet<TableRecipes1081655>();
        }
    
        public int cId { get; set; }
        [DisplayName("名稱")]
        [Required(ErrorMessage = "名稱不可空白")]
        [StringLength(20, ErrorMessage = "名稱不可超過20個字元")]
        public string name { get; set; }
        [DisplayName("密碼")]
        [Required(ErrorMessage = "密碼不可空白")]
        [StringLength(16, ErrorMessage = "密碼不可超過16個字元")]
        public string password { get; set; }
        [DisplayName("電話")]
        [StringLength(10, ErrorMessage = "電話只能10個字元",
            MinimumLength = 10)]
        public string phone { get; set; }
        [DisplayName("年齡")]
        public Nullable<int> age { get; set; }
        [DisplayName("城市")]
        [StringLength(20, ErrorMessage = "城市不可超過20個字元")]
        public string city { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableRecipes1081655> TableRecipes1081655 { get; set; }
    }
}
